- name: instalando apache no debian
  package:
   name: apache2
  when: ansible_os_family == "Debian"
  
- name: instalando pacotes no CentOS
  package:
   name: httpd
  when: ansible_os_family == "RedHat"
